name: Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:13.5.0-alphine3.10
    steps:
      - name: Log node versions
        run: |
          node -v
          cat /etc/os-release
          